### ISSUE TITLE
Traceback Error While running 

### ISSUE THREAD

**Issue by osamahamad** [andreyglauzer/VulnAlert#2]
Hi ,

If I run ```python3 VulnAlert.py -i -c /oneline/VulnAlert/utils/config/config.yml -t Telegram```

I receive : 

```
2021-03-21 01:19:51.930 INFO VulnAlert - start: Starting CVE Download Process
2021-03-21 01:19:51.930 INFO VulnAlert - download: Getting CVES
2021-03-21 01:19:51.930 INFO VulnAlert - download: Getting from https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2002.json.zip
Traceback (most recent call last):
  File "VulnAlert.py", line 511, in <module>
    alerts.start
  File "VulnAlert.py", line 411, in start
    self.download()
  File "VulnAlert.py", line 488, in download
    url = urlopen(urls)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

My config.yml is something similar to : 

```
database_path: 'utils/'
database_name: 'database.db'
splunk_dir: '/tmp/'
templatemail: 'utils/template/mail.html'
telegram: False
chat_id: 'Chat ID'
token: '17159XXXX:XXXXD91YYaGCTf2Ag0qSq8gO_SDHc'
mail: 'temp@gmail.com'
sendermail: 'temp@temp.com'
smtpmail: 'smtp.mail.com'
portmail: 587
passwdmail: 'passwd'
debug: False
score: 5.0

products:
    - name:
        id: 'magento'
```

**Comment by andreyglauzer** [comment]
Hey bro, I sent a new version. I created the old version a long time ago. I hope this new one can help you, any problem open a new issue
